PACKAGE_NAME="morse"
PACKAGE_VERSION="mm8108-2.0.0"

AUTOINSTALL="yes"

MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build KERNEL_SRC=/lib/modules/${kernelver}/build MORSE_TRACE_PATH=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build CONFIG_WLAN_VENDOR_MORSE=m CONFIG_MORSE_USB=y CONFIG_MORSE_USER_ACCESS=y CONFIG_MORSE_VENDOR_COMMAND=y CONFIG_MORSE_COUNTRY=@MORSE_COUNTRY@ CONFIG_ANDROID=n CONFIG_MORSE_MONITOR=n modules"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"

BUILT_MODULE_NAME[0]="dot11ah"
BUILT_MODULE_LOCATION[0]="dot11ah"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILT_MODULE_NAME[1]="morse"
BUILT_MODULE_LOCATION[1]="."
DEST_MODULE_LOCATION[1]="/updates/dkms"
